### ISSUE TITLE
Glitch with GBP to USD conversion

### ISSUE THREAD

**Issue by emfoster91** [clayton500k/streamlit#19]
Re the tables in the 'Individuals (Annual)' tab, I was a little confused by some of the results they were throwing out. For example, if 'GBP' is selected on the Home page and I then go to the 'Individuals (Annual)' tab, the first number (which relates to Paul Searle) is £1,438,029. If I then return to the Home page and change the currency to 'USD', the number for Paul Searle becomes $1,373,725. Surely the USD amount should be higher than the GBP amount?

**Comment by jeevatechoffice500k** [comment]
The biggest cause of this issue is the exchange rate from the Yahoo dataset, some months there is no exchange rate,so the income for those months may not be included in the sum.

**Comment by jeevatechoffice500k** [comment]
I have tried to fix it by excluding the NA value for Adjust Close and Including the next recent value. I have spent a couple of hours fixing it, but no progress...
Please input your Idea or technique here brother, Or can we include an additional column in the bank tab for EX Rate?

**Comment by jeevatechoffice500k** [comment]
Issue was resolved with the help of Clayton's suggestion in merge method

**Comment by emfoster91** [comment]
I've checked the development branch and this does seem resolved. 

Well done Jeeva!!

**Comment by emfoster91** [comment]
I thought this issue was resolved, but Ben Hadfield just looked at it and said he couldn't see any difference.

I just logged into the Development Branch and indeed it is still returning a lower number for Paul Searle in USD then it does for GBP

**Comment by clayton500k** [comment]
Thanks Edy, apologies, my previous fix was still missing dates.

I have now gone from taking the 1st of every month to taking the average exchange rate for every month. I now merge that in by matching on the year/month (rather than the exact date) and it gives more intuitive results (eg Paul Searle converted at an average rate of £1=$1.37)

Please close if you're happy and I will merge into main.
